### ISSUE TITLE
Docker를 활용한 AWS EKS 애플리케이션 배포 

### ISSUE THREAD

**Issue by stunstunstun** [stunstunstun/dietxurl#5]
## TODO

- [x] Docker 이미지 생성 
- [ ] Docker 이미지를 AWS ECR 에 업로드 
- [ ] Spring Boot 애플리케이션 EC2 배포 
- [ ] Spring Boot 애플리케이션 ECS 배포 
- [ ] 통합 테스트

## References
- https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/deploy-java-microservices-on-amazon-eks-by-using-amazon-ecr-and-eksctl.html
